"""
Slack notification helpers. Called from creatives/services.py after generation.
All calls are fire-and-forget — exceptions are swallowed so a Slack failure
never breaks a generation job.
"""
import requests as http_requests
from django.conf import settings

SLACK_API = 'https://slack.com/api'


def _post(token, method, payload):
    try:
        resp = http_requests.post(
            f'{SLACK_API}/{method}',
            headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'},
            json=payload,
            timeout=10,
        )
        return resp.json()
    except Exception:
        return {}


def _get_channels(workspace, content_type):
    """Return (SlackChannel, bot_token) tuples for channels that auto-post this content_type."""
    try:
        channels = workspace.slack_channels.select_related('installation').all()
        result = []
        for sc in channels:
            enabled = sc.content_types or []
            auto = sc.auto_post_types or []
            if content_type in enabled and content_type in auto:
                result.append((sc, sc.installation.bot_token))
        return result
    except Exception:
        return []


def _mark_posted(creative_ids):
    """Add 'Slack Posted' tag to the given GeneratedCreative ids."""
    if not creative_ids:
        return
    try:
        from apps.creatives.models import GeneratedCreative, CreativeTag
        creatives = list(GeneratedCreative.objects.filter(id__in=creative_ids).select_related('workspace'))
        if not creatives:
            return
        workspace = creatives[0].workspace
        tag, _ = CreativeTag.objects.get_or_create(
            workspace=workspace, name='Slack Posted',
            defaults={'color': '#8B5CF6'},
        )
        for c in creatives:
            c.tags.add(tag)
    except Exception:
        pass


def _user_label(user):
    if not user:
        return None
    name = user.get_full_name().strip()
    return name or user.email


def notify_slack_generation(workspace, job, image_urls, creative_ids=None):
    channels = _get_channels(workspace, 'creatives')
    if not channels or not image_urls:
        return

    campaign  = job.campaign.name if job.campaign else 'Creatives'
    count     = len(image_urls)
    base_url  = settings.SITE_BASE_URL
    by        = _user_label(job.created_by)

    blocks = [
        {
            'type': 'section',
            'text': {
                'type': 'mrkdwn',
                'text': (
                    f':sparkles: *{count} new creative{"s" if count > 1 else ""} generated*\n'
                    f'*Campaign:* {campaign}  |  *Model:* {job.model_name}  |  *Format:* {job.aspect_ratio}'
                    + (f'\n*Generated by:* {by}' if by else '')
                ),
            },
        },
    ]
    for i, url in enumerate(image_urls[:4], 1):
        blocks.append({'type': 'image', 'image_url': url, 'alt_text': f'{campaign} — Variant {i}',
                        'title': {'type': 'plain_text', 'text': f'Variant {i}'}})
    if count > 4:
        blocks.append({'type': 'context', 'elements': [
            {'type': 'mrkdwn', 'text': f'_+{count - 4} more in your <{base_url}/dashboard|Troxa dashboard>_'}]})
    blocks.append({'type': 'actions', 'elements': [{
        'type': 'button', 'text': {'type': 'plain_text', 'text': 'Open Dashboard'},
        'url': f'{base_url}/dashboard', 'style': 'primary',
    }]})

    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f'{count} creative{"s" if count > 1 else ""} generated — {campaign}',
            'blocks': blocks,
        })

    _mark_posted(creative_ids)


def notify_slack_video(workspace, vjob):
    channels = _get_channels(workspace, 'videos')
    if not channels or not vjob.video_url:
        return

    creative_name = (vjob.source_creative.name or '') if vjob.source_creative else ''
    base_url = settings.SITE_BASE_URL

    blocks = [
        {
            'type': 'section',
            'text': {
                'type': 'mrkdwn',
                'text': (
                    f':clapper: *Video generated*\n'
                    + (f'*Creative:* {creative_name}\n' if creative_name else '')
                    + f'<{vjob.video_url}|Download video>'
                ),
            },
        },
        {'type': 'actions', 'elements': [{
            'type': 'button', 'text': {'type': 'plain_text', 'text': 'Open Dashboard'},
            'url': f'{base_url}/dashboard', 'style': 'primary',
        }]},
    ]

    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f':clapper: Video ready — {creative_name}',
            'blocks': blocks,
        })

    if vjob.source_creative_id:
        _mark_posted([str(vjob.source_creative_id)])


def notify_slack_logo_save(workspace, image_urls, user=None, creative_ids=None):
    channels = _get_channels(workspace, 'logos')
    if not channels or not image_urls:
        return

    count    = len(image_urls)
    base_url = settings.SITE_BASE_URL
    by       = _user_label(user)

    blocks = [{'type': 'section', 'text': {'type': 'mrkdwn',
        'text': f':art: *Logo applied* — {count} image{"s" if count != 1 else ""} saved'
                + (f'\n*Saved by:* {by}' if by else ''),
    }}]
    for i, url in enumerate(image_urls[:4], 1):
        blocks.append({'type': 'image', 'image_url': url, 'alt_text': f'With Logo — Variant {i}',
                        'title': {'type': 'plain_text', 'text': f'Variant {i}'}})
    if count > 4:
        blocks.append({'type': 'context', 'elements': [
            {'type': 'mrkdwn', 'text': f'_+{count - 4} more in your <{base_url}/dashboard|Troxa dashboard>_'}]})
    blocks.append({'type': 'actions', 'elements': [{
        'type': 'button', 'text': {'type': 'plain_text', 'text': 'Open Dashboard'},
        'url': f'{base_url}/dashboard', 'style': 'primary',
    }]})

    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f':art: Logo applied — {count} image{"s" if count != 1 else ""} saved',
            'blocks': blocks,
        })

    _mark_posted(creative_ids)


def notify_slack_automation_start(workspace, automation):
    channels = _get_channels(workspace, 'automation')
    if not channels:
        return
    by = _user_label(automation.created_by)
    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f':robot_face: Automation "{automation.name}" started',
            'blocks': [{'type': 'section', 'text': {'type': 'mrkdwn',
                'text': (f':robot_face: *Automation started*\n*{automation.name}* — generating '
                         f'{automation.num_images} image{"s" if automation.num_images != 1 else ""}'
                         + (f'\n*Triggered by:* {by}' if by else '')),
            }}],
        })


def notify_slack_automation_done(workspace, automation, image_urls):
    channels = _get_channels(workspace, 'automation')
    if not channels:
        return

    count    = len(image_urls)
    base_url = settings.SITE_BASE_URL
    by       = _user_label(automation.created_by)

    blocks = [{'type': 'section', 'text': {'type': 'mrkdwn',
        'text': (f':white_check_mark: *Automation complete*\n*{automation.name}* — '
                 f'{count} image{"s" if count != 1 else ""} generated'
                 + (f'\n*Generated by:* {by}' if by else '')),
    }}]
    for i, url in enumerate(image_urls[:4], 1):
        blocks.append({'type': 'image', 'image_url': url,
                        'alt_text': f'{automation.name} — Variant {i}',
                        'title': {'type': 'plain_text', 'text': f'Variant {i}'}})
    if count > 4:
        blocks.append({'type': 'context', 'elements': [
            {'type': 'mrkdwn', 'text': f'_+{count - 4} more in your <{base_url}/dashboard|Troxa dashboard>_'}]})
    blocks.append({'type': 'actions', 'elements': [{
        'type': 'button', 'text': {'type': 'plain_text', 'text': 'Open Dashboard'},
        'url': f'{base_url}/dashboard', 'style': 'primary',
    }]})

    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f':white_check_mark: Automation "{automation.name}" complete — {count} images',
            'blocks': blocks,
        })


def notify_slack_automation_error(workspace, automation, error_msg):
    channels = _get_channels(workspace, 'automation')
    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f':x: Automation "{automation.name}" failed',
            'blocks': [{'type': 'section', 'text': {'type': 'mrkdwn',
                'text': f':x: *Automation failed*\n*{automation.name}*\n```{error_msg}```',
            }}],
        })


def notify_slack_edit(workspace, creative, user=None):
    """
    Post a single edited creative to channels that have 'logos' (Edits) content type enabled.
    Called after AiEdit or SaveCanvas saves a creative with is_edited=True.
    """
    channels = _get_channels(workspace, 'logos')
    if not channels:
        return

    url = creative.image_url
    if not url:
        return

    base_url = settings.SITE_BASE_URL
    by = _user_label(user)

    blocks = [
        {
            'type': 'section',
            'text': {
                'type': 'mrkdwn',
                'text': (
                    f':pencil2: *Edit saved — {creative.name}*'
                    + (f'\n*Campaign:* {creative.campaign.name}' if creative.campaign else '')
                    + (f'\n*Saved by:* {by}' if by else '')
                ),
            },
        },
        {'type': 'image', 'image_url': url, 'alt_text': creative.name,
         'title': {'type': 'plain_text', 'text': creative.name[:75]}},
        {'type': 'actions', 'elements': [{
            'type': 'button', 'text': {'type': 'plain_text', 'text': 'Open Dashboard'},
            'url': f'{base_url}/dashboard', 'style': 'primary',
        }]},
    ]

    for sc, token in channels:
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': f':pencil2: Edit saved — {creative.name}',
            'blocks': blocks,
        })

    _mark_posted([str(creative.id)])


def post_creatives_to_channel(sc, token, creatives):
    """
    Manually post a list of GeneratedCreative objects to a specific channel.
    Called from the manual post endpoint.
    """
    base_url = settings.SITE_BASE_URL
    for creative in creatives:
        url = creative.logo_applied_url or creative.image_url
        if not url:
            continue
        blocks = [
            {'type': 'image', 'image_url': url, 'alt_text': creative.name,
             'title': {'type': 'plain_text', 'text': creative.name[:75]}},
            {'type': 'context', 'elements': [{'type': 'mrkdwn',
                'text': (f'*{creative.name}*'
                         + (f'  |  Campaign: {creative.campaign.name}' if creative.campaign else '')
                         + f'  |  {creative.aspect_ratio}  |  {creative.media_type}'),
            }]},
            {'type': 'actions', 'elements': [{
                'type': 'button', 'text': {'type': 'plain_text', 'text': 'Open Dashboard'},
                'url': f'{base_url}/dashboard', 'style': 'primary',
            }]},
        ]
        _post(token, 'chat.postMessage', {
            'channel': sc.channel_id,
            'text': creative.name,
            'blocks': blocks,
        })

    _mark_posted([str(c.id) for c in creatives])
