"""
Queueing a generation job.

One place where a job gets built, so every surface that can start a generation
— the Generate tab, and now a Slack modal — agrees on the credit rules, the
field defaults and what runs afterwards. Authorization deliberately stays with
the caller: *who* may generate is a question about the surface (a signed-in
user's role, a connected Slack channel), not about the job itself.
"""
import logging

from apps.activity.utils import log_event
from apps.billing.models import Subscription

logger = logging.getLogger(__name__)

# Per-image credit cost. Mirrors MODEL_CREDIT_COST in services.py, which is
# what actually gets deducted once the images come back.
MODEL_CREDIT_COST = {
    'Nano Banana Pro':  2,
    'GPT Image 2':      2,
    'Seedream 5.0 Pro': 2,
}
DEFAULT_MODEL = 'Nano Banana 2'
# What the Generate tab sends when it is left in 'auto' mode — Slack's minimal
# modal doesn't ask for a model, so it has to pick the same one the dashboard
# would have picked for the same input (see useGenerationSettings.js).
AUTO_MODE_MODEL = 'GPT Image 2'


def credit_cost(num_images, model_name=DEFAULT_MODEL):
    return num_images * MODEL_CREDIT_COST.get(model_name, 1)


def credit_error(ws, num_images, model_name=DEFAULT_MODEL):
    """None when the workspace can afford this, otherwise a dict describing why not."""
    required = credit_cost(num_images, model_name)
    try:
        sub = ws.subscription
    except Subscription.DoesNotExist:
        return {
            'error': 'insufficient_credits',
            'detail': 'No credit account found. Please contact support.',
            'status': 402,
        }
    if sub.plan.unlimited_usage:
        return None
    available = sub.credits_available
    if available < required:
        return {
            'error': 'insufficient_credits',
            'detail': (f'You need {required} credit(s) but only have {available} left '
                       f'this month. Upgrade your plan or add bonus credits.'),
            'available': available,
            'required': required,
            'upgrade_required': True,
            'status': 402,
        }
    return None


def start_generation(ws, params, *, user=None, origin='dashboard', origin_channel=''):
    """
    Build and queue a generation job. Returns (job, error) — exactly one is None.

    `error` is a plain dict so each caller can render it in its own idiom: the
    API turns it into a 402 body, Slack into an inline modal error.

    `user` may be None: a generation started from a Slack channel has no Troxa
    user behind it, and created_by is nullable. `origin` is what the gallery
    falls back to for the "generated by" label in that case.
    """
    from .models import GenerationJob
    from .services import generate_job_async

    d = params
    num_images = int(d.get('num_images', 2))
    model_name = d.get('model_name') or DEFAULT_MODEL

    err = credit_error(ws, num_images, model_name)
    if err:
        return None, err

    campaign = ws.campaigns.filter(id=d['campaign_id']).first() if d.get('campaign_id') else None
    disclaimer = ws.disclaimers.filter(id=d['disclaimer_id']).first() if d.get('disclaimer_id') else None
    logo = ws.logos.filter(id=d['logo_id']).first() if d.get('logo_id') else None
    character = ws.characters.filter(id=d['character_id']).first() if d.get('character_id') else None

    job = GenerationJob.objects.create(
        workspace=ws,
        created_by=user,
        origin=origin,
        origin_channel=origin_channel,
        campaign=campaign,
        disclaimer=disclaimer,
        model_name=model_name,
        aspect_ratio=d.get('aspect_ratio', '1:1'),
        resolution=d.get('resolution', '1K'),
        num_images=num_images,
        output_format=d.get('output_format', 'png'),
        generate_new_character=bool(d.get('generate_new_character', False)),
        image_size=d.get('image_size') or '',
        image_quality=d.get('image_quality') or 'high',
        style=d.get('style') or '',
        extra_prompt=d.get('extra_prompt') or '',
        negative_prompt=d.get('negative_prompt') or '',
        use_fingerprint=bool(d.get('use_fingerprint', False)),
        blend_weight=int(d.get('blend_weight', 50)),
        simplicity_weight=(int(d['simplicity_weight'])
                           if d.get('simplicity_mode') and d.get('simplicity_weight') is not None
                           else None),
        generation_mode=d.get('generation_mode', 'auto'),
        logo=logo,
        character=character,
    )

    static_ids = d.get('static_ids') or []
    if static_ids:
        job.reference_creatives.set(ws.creatives.filter(id__in=static_ids, media_type='Photo'))

    # A pre-built master prompt (Prompt Architect) lets the worker skip the DNA
    # build step entirely.
    prebuilt = (d.get('prebuilt_master_prompt') or '').strip()
    if prebuilt:
        job.master_prompt = prebuilt
        job.save(update_fields=['master_prompt'])

    log_event(ws, user, 'generation_started', f'Generation job #{job.id} queued',
              {'origin': origin, 'actor': d.get('actor') or ''})
    generate_job_async(job.id)
    return job, None
