# Generated by Django 4.2.30 on 2026-08-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_kit', '0007_studio_job'),
        ('creatives', '0015_generation_job_character'),
        ('accounts', '0006_mgmt_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_profile', models.JSONField(blank=True, default=dict)),
                ('brand_profile_version', models.PositiveIntegerField(default=0)),
                ('visual_dna', models.JSONField(blank=True, default=dict)),
                ('negative_patterns', models.JSONField(blank=True, default=dict)),
                ('visual_dna_version', models.PositiveIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=10)),
                ('based_on_image_count', models.PositiveIntegerField(default=0)),
                ('last_full_recreate_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='accounts.workspace')),
            ],
            options={
                'db_table': 'fingerprint_brandfingerprint',
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('source', models.CharField(choices=[('gallery', 'Gallery upload'), ('generation', 'Generation result')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='positive', max_length=10)),
                ('analysis', models.JSONField(default=dict)),
                ('included_in_fingerprint_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_records', to='creatives.generatedcreative')),
                ('winning_static', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_records', to='brand_kit.winningstatic')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_corpus', to='accounts.workspace')),
            ],
            options={
                'db_table': 'fingerprint_imageanalysisrecord',
                'indexes': [models.Index(fields=['workspace', 'included_in_fingerprint_version'], name='fingerprint_workspa_6d72ba_idx'), models.Index(fields=['workspace', 'source'], name='fingerprint_workspa_f6eeb6_idx')],
            },
        ),
    ]
