# Generated by Django 4.2.30 on 2026-08-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0008_campaign_campaign_brief_campaign_objective_and_more'),
        ('accounts', '0006_mgmt_permission'),
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_insight', to='brand_kit.campaign')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_insights', to='accounts.workspace')),
            ],
            options={
                'db_table': 'fingerprint_campaignmarketinsight',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignCreativeBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_version', models.IntegerField(default=0)),
                ('briefs', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_briefs', to='brand_kit.campaign')),
                ('market_insight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fingerprint.campaignmarketinsight')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_briefs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'fingerprint_campaigncreativebrief',
                'ordering': ['-created_at'],
            },
        ),
    ]
