# Generated by Django 4.2.30 on 2026-08-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mgmt_permission'),
        ('fingerprint', '0002_campaignmarketinsight_campaigncreativebrief'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTrendBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ideas', models.JSONField(default=list)),
                ('landscape_summary', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_briefs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'fingerprint_workspacetrendbrief',
                'ordering': ['-created_at'],
            },
        ),
    ]
