# Generated by Django 4.2.30 on 2026-07-01 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ad_name', models.CharField(blank=True, max_length=512)),
                ('campaign_id', models.CharField(blank=True, max_length=64)),
                ('campaign_name', models.CharField(blank=True, max_length=512)),
                ('adset_id', models.CharField(blank=True, max_length=64)),
                ('adset_name', models.CharField(blank=True, max_length=512)),
                ('ad_status', models.CharField(blank=True, max_length=32)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creative_image_path', models.CharField(blank=True, max_length=500)),
                ('creative_image_url', models.URLField(blank=True, max_length=2000)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('regs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ftp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchases', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('raw_insights', models.JSONField(blank=True, null=True)),
                ('raw_ad', models.JSONField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('personal_rating', models.IntegerField(blank=True, null=True)),
                ('success_rating', models.IntegerField(blank=True, null=True)),
                ('labeled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labeled_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spend', 'ad_name'],
            },
        ),
    ]
