# Generated by Django 4.2.30 on 2026-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_lab', '0002_add_cost_per_ftp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='cost_per_reg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
