# Generated by Django 4.2.30 on 2026-06-18 09:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brand_kit", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedCreative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=1000)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
                ("logo_applied_url", models.URLField(blank=True, max_length=1000)),
                ("media_type", models.CharField(default="Photo", max_length=20)),
                ("logo_position", models.CharField(default="No Logo", max_length=30)),
                ("status", models.CharField(default="Ready", max_length=30)),
                ("compliance", models.CharField(default="Verified", max_length=30)),
                ("aspect_ratio", models.CharField(default="1:1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="brand_kit.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="Nano Banana 2", max_length=100),
                ),
                ("aspect_ratio", models.CharField(default="1:1", max_length=20)),
                ("resolution", models.CharField(default="1K", max_length=10)),
                ("num_images", models.SmallIntegerField(default=2)),
                ("output_format", models.CharField(default="png", max_length=10)),
                ("generate_new_character", models.BooleanField(default=False)),
                (
                    "image_size",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("image_quality", models.CharField(default="high", max_length=20)),
                (
                    "style",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("extra_prompt", models.TextField(blank=True, default="", null=True)),
                ("master_prompt", models.TextField(blank=True)),
                ("vibe_and_atmosphere", models.TextField(blank=True)),
                (
                    "recommended_colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=7),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("character_archetype", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("captioning", "Captioning"),
                            ("generating_prompt", "Generating Prompt"),
                            ("generating_images", "Generating Images"),
                            ("saving", "Saving"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="captioning",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="brand_kit.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disclaimer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="brand_kit.disclaimer",
                    ),
                ),
                (
                    "statics",
                    models.ManyToManyField(blank=True, to="brand_kit.winningstatic"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogoJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creatives.generationjob",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logo_jobs",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogoJobImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="logo_results/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="creatives.logojob",
                    ),
                ),
                (
                    "source_creative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="creatives.generatedcreative",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="generatedcreative",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creatives",
                to="creatives.generationjob",
            ),
        ),
        migrations.AddField(
            model_name="generatedcreative",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creatives",
                to="accounts.workspace",
            ),
        ),
        migrations.CreateModel(
            name="VideoJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_image_url", models.URLField(max_length=2000)),
                ("prompt", models.TextField(default="Smooth cinematic motion")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(blank=True, max_length=2000)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_creative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_jobs",
                        to="creatives.generatedcreative",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_jobs",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="creatives_v_workspa_52a231_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["workspace", "status"], name="creatives_g_workspa_a2710e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="creatives_g_workspa_bd83f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcreative",
            index=models.Index(
                fields=["workspace", "campaign"], name="creatives_g_workspa_b50e36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcreative",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="creatives_g_workspa_eeb833_idx",
            ),
        ),
    ]
