# Generated by Django 4.2.30 on 2026-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='fal_request_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
