# Generated by Django 4.2.30 on 2026-06-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0001_initial'),
        ('creatives', '0002_video_job_fal_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_kit.logo'),
        ),
    ]
