# Generated by Django 4.2.30 on 2026-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0005_videojob_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='generation_mode',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
