# Generated by Django 4.2.30 on 2026-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0006_add_generation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcreative',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
