# Generated by Django 4.2.30 on 2026-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0007_add_creative_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcreative',
            name='in_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
