# Generated by Django 4.2.30 on 2026-07-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_workspace_code_and_counter'),
        ('creatives', '0008_add_in_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='generated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='google_drive_synced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='is_edited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='meta_linked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='slack_posted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='source',
            field=models.CharField(choices=[('troxa_generated', 'Troxa Generated'), ('uploaded', 'Uploaded')], db_index=True, default='troxa_generated', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_creatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='creative_uploads/'),
        ),
        migrations.AlterField(
            model_name='generatedcreative',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='generatedcreative',
            name='logo_applied_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='generatedcreative',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddIndex(
            model_name='generatedcreative',
            index=models.Index(fields=['workspace', 'source'], name='creatives_g_workspa_72244d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcreative',
            index=models.Index(fields=['workspace', 'media_type'], name='creatives_g_workspa_675722_idx'),
        ),
        migrations.AddField(
            model_name='creativetag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativetag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_tags', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='creatives', to='creatives.creativetag'),
        ),
        migrations.AlterUniqueTogether(
            name='creativetag',
            unique_together={('workspace', 'name')},
        ),
    ]
