# Generated by Django 4.2.30 on 2026-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0009_creativetag_generatedcreative_generated_by_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedcreative',
            new_name='creatives_workspa_72ab6b_idx',
            old_name='creatives_g_workspa_b50e36_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedcreative',
            new_name='creatives_workspa_df2343_idx',
            old_name='creatives_g_workspa_eeb833_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedcreative',
            new_name='creatives_workspa_11402c_idx',
            old_name='creatives_g_workspa_72244d_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedcreative',
            new_name='creatives_workspa_7dca73_idx',
            old_name='creatives_g_workspa_675722_idx',
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='caption_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='legacy_static_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='generatedcreative',
            name='performance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='reference_creatives',
            field=models.ManyToManyField(blank=True, related_name='used_as_reference_in_jobs', to='creatives.generatedcreative'),
        ),
        migrations.AlterModelTable(
            name='generatedcreative',
            table='creatives',
        ),
    ]
