# Generated by Django 4.2.30 on 2026-07-08 20:08 — hand-edited to insert a
# data migration between adding `created_by` and dropping the old
# `generated_by` name-snapshot string, so the FK can be backfilled from
# job.created_by / uploaded_by / a best-effort name match before the string
# is gone for good.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_created_by(apps, schema_editor):
    GeneratedCreative = apps.get_model('creatives', 'GeneratedCreative')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    # Best-effort name -> user lookup for rows that only ever had the
    # denormalized `generated_by` string (old ai-edit/erase/save-canvas
    # results created before authorship was tracked via a real FK).
    name_to_user = {}
    for u in User.objects.all():
        full = f'{u.first_name} {u.last_name}'.strip()
        name_to_user.setdefault(full or u.email, u)

    # 1. AI-generated creatives — attribute to whoever kicked off the job.
    qs = GeneratedCreative.objects.filter(job__isnull=False).select_related('job__created_by')
    for creative in qs.iterator():
        if creative.job.created_by_id:
            GeneratedCreative.objects.filter(pk=creative.pk).update(created_by_id=creative.job.created_by_id)

    # 2. Directly uploaded (job-less) creatives — attribute to the uploader.
    qs = GeneratedCreative.objects.filter(job__isnull=True, uploaded_by__isnull=False)
    for creative in qs.iterator():
        GeneratedCreative.objects.filter(pk=creative.pk).update(created_by_id=creative.uploaded_by_id)

    # 3. Remaining job-less, uploader-less rows — match the old name string.
    qs = (GeneratedCreative.objects
          .filter(job__isnull=True, uploaded_by__isnull=True, created_by__isnull=True)
          .exclude(generated_by=''))
    for creative in qs.iterator():
        user = name_to_user.get(creative.generated_by)
        if user:
            GeneratedCreative.objects.filter(pk=creative.pk).update(created_by_id=user.id)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creatives', '0012_backfill_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcreative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_creatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_created_by, reverse_noop),
        migrations.RemoveField(
            model_name='generatedcreative',
            name='generated_by',
        ),
    ]
