# Generated by Django 4.2.30 on 2026-07-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0013_generated_by_to_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcreative',
            name='google_drive_synced',
        ),
        migrations.RemoveField(
            model_name='generatedcreative',
            name='meta_linked',
        ),
        migrations.RemoveField(
            model_name='generatedcreative',
            name='slack_posted',
        ),
    ]
