# Generated by Django 4.2.30 on 2026-07-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0004_character_image_caption'),
        ('creatives', '0014_remove_system_bool_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='brand_kit.character'),
        ),
    ]
