# Generated by Django 4.2.30 on 2026-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0015_generation_job_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='use_fingerprint',
            field=models.BooleanField(default=False),
        ),
    ]
