# Generated by Django 4.2.30 on 2026-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0016_generationjob_use_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='blend_weight',
            field=models.SmallIntegerField(default=50),
        ),
    ]
