# Generated by Django 4.2.30 on 2026-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0019_creativequalityscore'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creativequalityscore',
            new_name='creatives_c_status_d316ae_idx',
            old_name='creatives_c_status_idx',
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='generation_mode',
            field=models.CharField(default='auto', max_length=20),
        ),
    ]
