# Generated by Django 4.2.30 on 2026-09-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0020_generation_mode_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='origin',
            field=models.CharField(default='dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='origin_channel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
