# Generated by Django 4.2.30 on 2026-09-23 19:06

from django.db import migrations, models


def mark_uploads_as_references(apps, schema_editor):
    """
    Everything uploaded so far was uploaded to be used as reference material —
    that was the only reason to put an outside image in. They keep that meaning
    under the new field instead of being silently demoted to nothing.
    """
    Creative = apps.get_model('creatives', 'GeneratedCreative')
    Creative.objects.filter(source='uploaded').update(is_reference=True)


def unmark(apps, schema_editor):
    Creative = apps.get_model('creatives', 'GeneratedCreative')
    Creative.objects.update(is_reference=False)


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0021_generationjob_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcreative',
            name='is_reference',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(mark_uploads_as_references, unmark),
    ]
