# Generated by Django 4.2.30 on 2026-06-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('drive_integration', '0002_per_user_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveconnection',
            name='generations_folder_id',
        ),
        migrations.AddField(
            model_name='driveconnection',
            name='root_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='DriveWorkspaceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_folder_id', models.CharField(blank=True, max_length=200)),
                ('images_folder_id', models.CharField(blank=True, max_length=200)),
                ('videos_folder_id', models.CharField(blank=True, max_length=200)),
                ('logos_folder_id', models.CharField(blank=True, max_length=200)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_folders', to='drive_integration.driveconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_folders', to='accounts.workspace')),
            ],
            options={
                'unique_together': {('connection', 'workspace')},
            },
        ),
    ]
