# Generated by Django 4.2.30 on 2026-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_integration', '0003_workspace_folder_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveworkspacefolder',
            name='custom_images_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driveworkspacefolder',
            name='custom_logos_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driveworkspacefolder',
            name='custom_videos_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driveworkspacefolder',
            name='sync_creatives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driveworkspacefolder',
            name='sync_logos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driveworkspacefolder',
            name='sync_videos',
            field=models.BooleanField(default=True),
        ),
    ]
