# Generated by Django 4.2.30 on 2026-10-07 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_mgmt_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=32)),
                ('page_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='accounts.workspace')),
            ],
            options={
                'ordering': ['page_name', 'page_id'],
                'unique_together': {('workspace', 'page_id')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_archive_id', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('display_format', models.CharField(blank=True, default='', max_length=32)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(blank=True, default='', max_length=128)),
                ('cta_type', models.CharField(blank=True, default='', max_length=64)),
                ('link_url', models.URLField(blank=True, default='', max_length=2000)),
                ('title', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('media', models.JSONField(blank=True, default=list)),
                ('cards', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='competitors.competitor')),
            ],
            options={
                'ordering': ['position', '-start_date'],
                'unique_together': {('competitor', 'ad_archive_id')},
            },
        ),
    ]
