# Generated by Django 4.2.30 on 2026-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorad',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='competitorad',
            name='analysis_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='competitorad',
            name='analysis_status',
            field=models.CharField(blank=True, choices=[('', 'Not yet'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='competitorad',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
