# Generated by Django 4.2.30 on 2026-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mgmt_permission'),
        ('competitors', '0002_ad_analysis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitor',
            name='country',
            field=models.CharField(default='US', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together={('workspace', 'page_id', 'country')},
        ),
    ]
