# Generated by Django 4.2.30 on 2026-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_linked',
            field=models.BooleanField(default=False),
        ),
    ]
