# Generated by Django 4.2.30 on 2026-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('analyst', 'Analyst')], default='analyst', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('analyst', 'Analyst')], default='analyst', max_length=20),
        ),
    ]
