# Generated by Django 4.2.30 on 2026-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_manager_viewer_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_data_user',
            field=models.BooleanField(default=False),
        ),
    ]
