# Generated by Django 4.2.30 on 2026-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_is_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='workspace',
            name='creative_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
