# Generated by Django 4.2.30 on 2026-07-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_code_and_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MgmtPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabs', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mgmt_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
