# Generated by Django 4.2.30 on 2026-06-18 09:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brand_kit", "0001_initial"),
        ("creatives", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("extra_prompt", models.TextField(blank=True)),
                (
                    "model_name",
                    models.CharField(default="Nano Banana 2", max_length=100),
                ),
                ("aspect_ratio", models.CharField(default="1:1", max_length=20)),
                ("resolution", models.CharField(default="1K", max_length=10)),
                ("image_size", models.CharField(blank=True, max_length=50)),
                ("image_quality", models.CharField(default="high", max_length=20)),
                ("num_images", models.SmallIntegerField(default=2)),
                ("output_format", models.CharField(default="png", max_length=10)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("schedule_time", models.TimeField(blank=True, null=True)),
                ("schedule_timezone", models.CharField(default="UTC", max_length=60)),
                (
                    "schedule_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="brand_kit.logo",
                    ),
                ),
                (
                    "statics",
                    models.ManyToManyField(blank=True, to="brand_kit.winningstatic"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automations",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="automation.automation",
                    ),
                ),
                (
                    "generation_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="creatives.generationjob",
                    ),
                ),
                (
                    "logo_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="creatives.logojob",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["automation", "started_at"],
                        name="automation__automat_f9dc12_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="automation",
            index=models.Index(
                fields=["workspace", "is_active"], name="automation__workspa_9dab91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automation",
            index=models.Index(
                fields=["next_run_at"], name="automation__next_ru_388f8d_idx"
            ),
        ),
    ]
