# Generated by Django 4.2.30 on 2026-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0010_merge_prep_schema'),
        ('automation', '0002_automation_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='reference_creatives',
            field=models.ManyToManyField(blank=True, related_name='used_as_reference_in_automations', to='creatives.generatedcreative'),
        ),
    ]
