# Generated by Django 4.2.30 on 2026-08-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0009_promo_extracted_text'),
        ('automation', '0004_migrate_statics_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='blend_weight',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='automation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_kit.campaign'),
        ),
        migrations.AddField(
            model_name='automation',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_kit.character'),
        ),
        migrations.AddField(
            model_name='automation',
            name='generation_mode',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='automation',
            name='simplicity_weight',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='use_fingerprint',
            field=models.BooleanField(default=True),
        ),
    ]
