# Generated by Django 4.2.30 on 2026-09-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0009_promo_extracted_text'),
        ('automation', '0006_automation_aspect_ratios'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='disclaimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_kit.disclaimer'),
        ),
        migrations.AddField(
            model_name='automation',
            name='negative_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
