# Generated by Django 4.2.30 on 2026-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='color_palette',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cta_texts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='must_avoid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='must_include',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='style_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tone_mood',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='campaign',
            name='visual_style',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
