# Generated by Django 4.2.30 on 2026-07-13 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_code_and_counter'),
        ('brand_kit', '0002_campaign_design_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='color_palette',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='cta_texts',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='must_avoid',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='must_include',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='style_notes',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tone_mood',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='visual_style',
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='characters/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brand_kit.character')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
