# Generated by Django 4.2.30 on 2026-07-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0003_character_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='characterimage',
            name='caption_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
