# Generated by Django 4.2.30 on 2026-07-14 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_code_and_counter'),
        ('brand_kit', '0004_character_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypographyPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Typography', max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('heading', models.CharField(default='Inter', max_length=100)),
                ('body', models.CharField(default='Inter', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typography_presets', to='accounts.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalettePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Palette', max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('colors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_presets', to='accounts.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
