# Generated by Django 4.2.30 on 2026-08-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_kit', '0007_studio_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_brief',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, choices=[('acquisition', 'Acquisition'), ('retention', 'Retention'), ('awareness', 'Brand Awareness'), ('reactivation', 'Reactivation'), ('event', 'Event / Seasonal')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_region',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
