# Generated by Django 4.2.30 on 2026-06-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('bot_token', models.CharField(max_length=300)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('connected_by_slack_user', models.CharField(blank=True, max_length=50)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='slack_integration.slackinstallation')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_channel', to='accounts.workspace')),
            ],
        ),
    ]
