# Generated by Django 4.2.30 on 2026-07-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_code_and_counter'),
        ('slack_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannel',
            name='content_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='slackchannel',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='slackchannel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_channels', to='accounts.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='slackchannel',
            unique_together={('workspace', 'channel_id')},
        ),
    ]
