# Generated by Django 4.2.30 on 2026-09-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0021_generationjob_origin'),
        ('slack_integration', '0003_slackchannel_auto_post_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackPostedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ts', models.CharField(max_length=32)),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('blocks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_messages', to='slack_integration.slackchannel')),
                ('creatives', models.ManyToManyField(related_name='slack_posts', to='creatives.generatedcreative')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('channel', 'message_ts')},
            },
        ),
    ]
