# Generated by Django 4.2.30 on 2026-10-07 17:19

from django.db import migrations, models
import django.db.models.deletion


def connect_from_channels(apps, schema_editor):
    """Workspaces connected today are the ones with channels; keep them connected."""
    SlackChannel = apps.get_model('slack_integration', 'SlackChannel')
    SlackConnection = apps.get_model('slack_integration', 'SlackConnection')
    for sc in SlackChannel.objects.order_by('-connected_at'):   # newest channel's team wins
        SlackConnection.objects.get_or_create(workspace_id=sc.workspace_id,
                                              defaults={'installation_id': sc.installation_id})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mgmt_permission'),
        ('slack_integration', '0004_posted_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='slack_integration.slackinstallation')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_connection', to='accounts.workspace')),
            ],
        ),
        migrations.RunPython(connect_from_channels, migrations.RunPython.noop),
    ]
