from django.urls import path
from .views import (
    CampaignView, CampaignDetailView,
    LogoView, LogoDetailView,
    CtaView, CtaDetailView,
    PromoView, PromoDetailView,
    StaticView, StaticDetailView,
    DisclaimerView, DisclaimerDetailView,
    CharacterView, CharacterDetailView,
    CharacterImageView, CharacterImageDetailView,
    CharacterGenerateView,
    StaticGenerateView,
    PromptStudioGenerateView, PromptStudioStatusView,
    PalettePresetView, PalettePresetDetailView,
    TypographyPresetView, TypographyPresetDetailView,
    ForbiddenKeywordView, ForbiddenKeywordDetailView,
)

urlpatterns = [
    path('campaigns/', CampaignView.as_view()),
    path('campaigns/<uuid:pk>/', CampaignDetailView.as_view()),
    path('logos/', LogoView.as_view()),
    path('logos/<int:pk>/', LogoDetailView.as_view()),
    path('ctas/', CtaView.as_view()),
    path('ctas/<int:pk>/', CtaDetailView.as_view()),
    path('promos/', PromoView.as_view()),
    path('promos/<int:pk>/', PromoDetailView.as_view()),
    path('statics/', StaticView.as_view()),
    path('statics/generate/', StaticGenerateView.as_view()),
    path('statics/<int:pk>/', StaticDetailView.as_view()),
    path('studio/generate/', PromptStudioGenerateView.as_view()),
    path('studio/status/<uuid:job_id>/', PromptStudioStatusView.as_view()),
    path('disclaimers/', DisclaimerView.as_view()),
    path('disclaimers/<int:pk>/', DisclaimerDetailView.as_view()),
    path('characters/', CharacterView.as_view()),
    path('characters/generate/', CharacterGenerateView.as_view()),
    path('characters/<uuid:pk>/', CharacterDetailView.as_view()),
    path('characters/<uuid:pk>/images/', CharacterImageView.as_view()),
    path('characters/<uuid:pk>/images/<int:img_pk>/', CharacterImageDetailView.as_view()),
    path('palette-presets/', PalettePresetView.as_view()),
    path('palette-presets/<uuid:pk>/', PalettePresetDetailView.as_view()),
    path('typography-presets/', TypographyPresetView.as_view()),
    path('typography-presets/<uuid:pk>/', TypographyPresetDetailView.as_view()),
    path('forbidden-keywords/', ForbiddenKeywordView.as_view()),
    path('forbidden-keywords/<int:pk>/', ForbiddenKeywordDetailView.as_view()),
]
